"""add hls_variants table

Revision ID: 62391564c4e4
Revises: b5e11b7ab2b5
Create Date: 2026-08-18 18:29:26.669816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62391564c4e4'
down_revision: Union[str, Sequence[str], None] = 'b5e11b7ab2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


hls_variants_table = sa.table(
    "hls_variants",
    sa.column("name", sa.String),
    sa.column("height", sa.Integer),
    sa.column("video_bitrate", sa.String),
    sa.column("audio_bitrate", sa.String),
    sa.column("bandwidth", sa.Integer),
    sa.column("resolution", sa.String),
    sa.column("sort_order", sa.Integer),
)

HLS_VARIANT_SEED = [
    {"name": "240p", "height": 240, "video_bitrate": "400k", "audio_bitrate": "96k", "bandwidth": 400_000, "resolution": "426x240", "sort_order": 0},
    {"name": "360p", "height": 360, "video_bitrate": "600k", "audio_bitrate": "96k", "bandwidth": 600_000, "resolution": "640x360", "sort_order": 1},
    {"name": "720p", "height": 720, "video_bitrate": "2000k", "audio_bitrate": "128k", "bandwidth": 2_000_000, "resolution": "1280x720", "sort_order": 2},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hls_variants',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('video_bitrate', sa.String(), nullable=False),
    sa.Column('audio_bitrate', sa.String(), nullable=False),
    sa.Column('bandwidth', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('sort_order')
    )
    # ### end Alembic commands ###

    op.bulk_insert(hls_variants_table, HLS_VARIANT_SEED)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hls_variants')
    # ### end Alembic commands ###
